apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: safe-settings-deployer
  namespace: safe-settings
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - serviceaccounts
      - services
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources:
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: safe-settings-deployer
  namespace: safe-settings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: safe-settings-deployer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: safe-settings-deployer@hacktron-462816.iam.gserviceaccount.com
